"""Crear tabla historial_clinico

Revision ID: 0f4b2a9bedb8
Revises: f11e2efb5677
Create Date: 2026-04-16 18:04:08.227417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4b2a9bedb8'
down_revision = 'f11e2efb5677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_clinico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=30), nullable=True),
    sa.Column('contacto_nombre_2', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono_2', sa.String(length=30), nullable=True),
    sa.Column('fuente_valoracion', sa.String(length=50), nullable=True),
    sa.Column('escolaridad', sa.String(length=100), nullable=True),
    sa.Column('sabe_leer', sa.Boolean(), nullable=True),
    sa.Column('sabe_escribir', sa.Boolean(), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('ocupacion_anterior', sa.String(length=150), nullable=True),
    sa.Column('ocupacion_actual', sa.String(length=150), nullable=True),
    sa.Column('domicilio_origen', sa.Text(), nullable=True),
    sa.Column('domicilio_actual', sa.Text(), nullable=True),
    sa.Column('nucleo_procedencia', sa.String(length=20), nullable=True),
    sa.Column('vivienda', sa.String(length=20), nullable=True),
    sa.Column('servicio_luz', sa.Boolean(), nullable=True),
    sa.Column('servicio_agua', sa.Boolean(), nullable=True),
    sa.Column('servicio_tel', sa.Boolean(), nullable=True),
    sa.Column('servicio_internet', sa.Boolean(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_clinico')
    # ### end Alembic commands ###
