"""Eliminar modulo historial clinico

Revision ID: 78fe98e30ff2
Revises: c51da19d5599
Create Date: 2026-04-16 12:46:46.763152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fe98e30ff2'
down_revision = 'c51da19d5599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_clinico')
    with op.batch_alter_table('actividad_social', schema=None) as batch_op:
        batch_op.alter_column('finalizado',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_social', schema=None) as batch_op:
        batch_op.alter_column('finalizado',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_table('historial_clinico',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha_registro', sa.DATETIME(), nullable=False),
    sa.Column('fecha_formulario', sa.DATE(), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('estado_civil', sa.VARCHAR(length=30), nullable=True),
    sa.Column('numero_contacto', sa.VARCHAR(length=20), nullable=True),
    sa.Column('domicilio', sa.VARCHAR(length=250), nullable=True),
    sa.Column('grado_escolaridad', sa.VARCHAR(length=50), nullable=True),
    sa.Column('familiar_confianza_nombre', sa.VARCHAR(length=120), nullable=True),
    sa.Column('familiar_confianza_telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('expectativas_participacion', sa.TEXT(), nullable=True),
    sa.Column('padece_enfermedad_actual', sa.BOOLEAN(), nullable=True),
    sa.Column('enfermedad_actual_detalle', sa.TEXT(), nullable=True),
    sa.Column('consume_medicamentos', sa.BOOLEAN(), nullable=True),
    sa.Column('medicamentos_detalle', sa.TEXT(), nullable=True),
    sa.Column('cirugias_previas', sa.BOOLEAN(), nullable=True),
    sa.Column('cirugias_detalle', sa.TEXT(), nullable=True),
    sa.Column('problemas_vision', sa.BOOLEAN(), nullable=True),
    sa.Column('problemas_audicion', sa.BOOLEAN(), nullable=True),
    sa.Column('impedimento_actividad_fisica', sa.BOOLEAN(), nullable=True),
    sa.Column('impedimento_detalle', sa.TEXT(), nullable=True),
    sa.Column('usa_dispositivo_apoyo', sa.BOOLEAN(), nullable=True),
    sa.Column('dispositivo_apoyo_detalle', sa.TEXT(), nullable=True),
    sa.Column('situacion_laboral_actual', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ocupacion_profesion_anterior', sa.VARCHAR(length=120), nullable=True),
    sa.Column('fuente_principal_ingresos', sa.VARCHAR(length=80), nullable=True),
    sa.Column('situacion_economica_actual', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cuenta_seguro_salud', sa.BOOLEAN(), nullable=True),
    sa.Column('recibe_ayuda_economica', sa.BOOLEAN(), nullable=True),
    sa.Column('tipo_vivienda', sa.VARCHAR(length=50), nullable=True),
    sa.Column('condicion_vivienda', sa.VARCHAR(length=50), nullable=True),
    sa.Column('personas_hogar', sa.INTEGER(), nullable=True),
    sa.Column('rol_hogar', sa.VARCHAR(length=80), nullable=True),
    sa.Column('participa_actividades_sociales', sa.BOOLEAN(), nullable=True),
    sa.Column('frecuencia_actividad_fisica', sa.VARCHAR(length=50), nullable=True),
    sa.Column('situacion_sociodemografica_adicional', sa.TEXT(), nullable=True),
    sa.Column('observaciones_entrevista', sa.TEXT(), nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
