"""Agregar escalas sociales GDS Katz Lawton

Revision ID: a53283de43b7
Revises: acb070de1796
Create Date: 2026-06-13 21:56:37.566809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53283de43b7'
down_revision = 'acb070de1796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_social_gds15',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_social_id', sa.Integer(), nullable=False),
    sa.Column('p1', sa.String(length=2), nullable=True),
    sa.Column('p2', sa.String(length=2), nullable=True),
    sa.Column('p3', sa.String(length=2), nullable=True),
    sa.Column('p4', sa.String(length=2), nullable=True),
    sa.Column('p5', sa.String(length=2), nullable=True),
    sa.Column('p6', sa.String(length=2), nullable=True),
    sa.Column('p7', sa.String(length=2), nullable=True),
    sa.Column('p8', sa.String(length=2), nullable=True),
    sa.Column('p9', sa.String(length=2), nullable=True),
    sa.Column('p10', sa.String(length=2), nullable=True),
    sa.Column('p11', sa.String(length=2), nullable=True),
    sa.Column('p12', sa.String(length=2), nullable=True),
    sa.Column('p13', sa.String(length=2), nullable=True),
    sa.Column('p14', sa.String(length=2), nullable=True),
    sa.Column('p15', sa.String(length=2), nullable=True),
    sa.Column('puntaje_total', sa.Integer(), nullable=True),
    sa.Column('interpretacion', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_social_id'], ['actividad_social.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_social_id')
    )
    op.create_table('actividad_social_katz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_social_id', sa.Integer(), nullable=False),
    sa.Column('bano', sa.Integer(), nullable=True),
    sa.Column('vestido', sa.Integer(), nullable=True),
    sa.Column('uso_sanitario', sa.Integer(), nullable=True),
    sa.Column('transferencias', sa.Integer(), nullable=True),
    sa.Column('continencia', sa.Integer(), nullable=True),
    sa.Column('alimentacion', sa.Integer(), nullable=True),
    sa.Column('puntaje_total', sa.Integer(), nullable=True),
    sa.Column('clasificacion_letra', sa.String(length=5), nullable=True),
    sa.Column('interpretacion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_social_id'], ['actividad_social.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_social_id')
    )
    op.create_table('actividad_social_lawton_brody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_social_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('transporte', sa.Integer(), nullable=True),
    sa.Column('compras', sa.Integer(), nullable=True),
    sa.Column('preparacion_alimentos', sa.Integer(), nullable=True),
    sa.Column('quehaceres_hogar', sa.Integer(), nullable=True),
    sa.Column('medicacion', sa.Integer(), nullable=True),
    sa.Column('manejo_dinero', sa.Integer(), nullable=True),
    sa.Column('puntaje_total', sa.Integer(), nullable=True),
    sa.Column('interpretacion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_social_id'], ['actividad_social.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_social_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad_social_lawton_brody')
    op.drop_table('actividad_social_katz')
    op.drop_table('actividad_social_gds15')
    # ### end Alembic commands ###
