"""Inicial

Revision ID: a604609cda0b
Revises: 
Create Date: 2026-05-06 16:24:31.429872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a604609cda0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividad_medica')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_medica',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=False),
    sa.Column('presion_arterial', sa.VARCHAR(length=20), nullable=True),
    sa.Column('glucosa', sa.VARCHAR(length=20), nullable=True),
    sa.Column('peso', sa.FLOAT(), nullable=True),
    sa.Column('observaciones', sa.VARCHAR(length=300), nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
