"""Crear actividad cognitiva UDS3

Revision ID: acb070de1796
Revises: 297978a0da26
Create Date: 2026-05-09 22:39:02.789065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb070de1796'
down_revision = '297978a0da26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_cognitiva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('idioma', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('moca_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moca_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_directos_total_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_directos_total_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_directos_longitud_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_directos_longitud_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_inversos_total_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_inversos_total_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_inversos_longitud_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('digitos_inversos_longitud_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_a_lineas_tiempo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_b_lineas_tiempo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_diferencial', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_ratio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_a_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_a_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_b_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_b_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_diferencial_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_diferencial_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_ratio_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trail_ratio_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mint_32_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mint_32_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_pm_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_p_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_p_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_m_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_m_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_pm_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_pm_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_animales', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_vegetales', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_animales_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_animales_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_vegetales_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluidez_vegetales_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_semantica_fonologica_diferencial', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_semantica_fonologica_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_semantica_fonologica_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_copia_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_recuerdo_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_copia_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_copia_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_recuerdo_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_recuerdo_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_retencion_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('benson_retencion_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_textual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_parafraseo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_textual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_parafraseo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_textual_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_textual_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_parafraseo_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_inmediato_parafraseo_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_textual_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_textual_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_parafraseo_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_diferido_parafraseo_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_retencion_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('craft_retencion_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('indice_errores', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('indice_errores_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('indice_errores_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diferencia_retencion_verbal_visual_z', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('diferencia_retencion_verbal_visual_percentil', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('perfil_cognitivo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sueno_indice_calidad', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sueno_estimacion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sueno_observaciones', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('moca_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('digitos_directos_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('digitos_directos_longitud',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('digitos_inversos_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('digitos_inversos_longitud',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mint_32_total',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('fluencia_p',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('fluencia_m',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('estimacion_global',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('creado_en')
        batch_op.drop_column('resumen_automatico')
        batch_op.drop_column('animales_total')
        batch_op.drop_column('craft_rd_parafraseo_25')
        batch_op.drop_column('craft_ri_44')
        batch_op.drop_column('benson_diferida')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('trail_a_estimacion')
        batch_op.drop_column('trail_puntuacion_ratio')
        batch_op.drop_column('fluencia_estimacion')
        batch_op.drop_column('trail_a_lineas_correctas')
        batch_op.drop_column('vegetales_total')
        batch_op.drop_column('craft_rd_44')
        batch_op.drop_column('craft_ri_parafraseo_25')
        batch_op.drop_column('finalizado')
        batch_op.drop_column('trail_puntuacion_diferencial')
        batch_op.drop_column('benson_inmediata')
        batch_op.drop_column('trail_b_lineas_correctas')
        batch_op.drop_column('fluencia_pm_promedio')
        batch_op.drop_column('fluidez_semantica_estimacion')
        batch_op.drop_column('trail_b_estimacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_cognitiva', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trail_b_estimacion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('fluidez_semantica_estimacion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('fluencia_pm_promedio', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trail_b_lineas_correctas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('benson_inmediata', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trail_puntuacion_diferencial', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('finalizado', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('craft_ri_parafraseo_25', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('craft_rd_44', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('vegetales_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('trail_a_lineas_correctas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fluencia_estimacion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('trail_puntuacion_ratio', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('trail_a_estimacion', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('actualizado_en', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('benson_diferida', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('craft_ri_44', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('craft_rd_parafraseo_25', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('animales_total', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('resumen_automatico', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('creado_en', sa.DATETIME(), nullable=True))
        batch_op.alter_column('estimacion_global',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('fluencia_m',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fluencia_p',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('mint_32_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('digitos_inversos_longitud',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('digitos_inversos_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('digitos_directos_longitud',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('digitos_directos_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('moca_total',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('sueno_observaciones')
        batch_op.drop_column('sueno_estimacion')
        batch_op.drop_column('sueno_indice_calidad')
        batch_op.drop_column('perfil_cognitivo')
        batch_op.drop_column('diferencia_retencion_verbal_visual_percentil')
        batch_op.drop_column('diferencia_retencion_verbal_visual_z')
        batch_op.drop_column('indice_errores_percentil')
        batch_op.drop_column('indice_errores_z')
        batch_op.drop_column('indice_errores')
        batch_op.drop_column('craft_retencion_percentil')
        batch_op.drop_column('craft_retencion_z')
        batch_op.drop_column('craft_diferido_parafraseo_percentil')
        batch_op.drop_column('craft_diferido_parafraseo_z')
        batch_op.drop_column('craft_diferido_textual_percentil')
        batch_op.drop_column('craft_diferido_textual_z')
        batch_op.drop_column('craft_inmediato_parafraseo_percentil')
        batch_op.drop_column('craft_inmediato_parafraseo_z')
        batch_op.drop_column('craft_inmediato_textual_percentil')
        batch_op.drop_column('craft_inmediato_textual_z')
        batch_op.drop_column('craft_diferido_parafraseo')
        batch_op.drop_column('craft_diferido_textual')
        batch_op.drop_column('craft_inmediato_parafraseo')
        batch_op.drop_column('craft_inmediato_textual')
        batch_op.drop_column('benson_retencion_percentil')
        batch_op.drop_column('benson_retencion_z')
        batch_op.drop_column('benson_recuerdo_percentil')
        batch_op.drop_column('benson_recuerdo_z')
        batch_op.drop_column('benson_copia_percentil')
        batch_op.drop_column('benson_copia_z')
        batch_op.drop_column('benson_recuerdo_total')
        batch_op.drop_column('benson_copia_total')
        batch_op.drop_column('fluencia_semantica_fonologica_percentil')
        batch_op.drop_column('fluencia_semantica_fonologica_z')
        batch_op.drop_column('fluencia_semantica_fonologica_diferencial')
        batch_op.drop_column('fluidez_vegetales_percentil')
        batch_op.drop_column('fluidez_vegetales_z')
        batch_op.drop_column('fluidez_animales_percentil')
        batch_op.drop_column('fluidez_animales_z')
        batch_op.drop_column('fluidez_vegetales')
        batch_op.drop_column('fluidez_animales')
        batch_op.drop_column('fluencia_pm_percentil')
        batch_op.drop_column('fluencia_pm_z')
        batch_op.drop_column('fluencia_m_percentil')
        batch_op.drop_column('fluencia_m_z')
        batch_op.drop_column('fluencia_p_percentil')
        batch_op.drop_column('fluencia_p_z')
        batch_op.drop_column('fluencia_pm_total')
        batch_op.drop_column('mint_32_percentil')
        batch_op.drop_column('mint_32_z')
        batch_op.drop_column('trail_ratio_percentil')
        batch_op.drop_column('trail_ratio_z')
        batch_op.drop_column('trail_diferencial_percentil')
        batch_op.drop_column('trail_diferencial_z')
        batch_op.drop_column('trail_b_percentil')
        batch_op.drop_column('trail_b_z')
        batch_op.drop_column('trail_a_percentil')
        batch_op.drop_column('trail_a_z')
        batch_op.drop_column('trail_ratio')
        batch_op.drop_column('trail_diferencial')
        batch_op.drop_column('trail_b_lineas_tiempo')
        batch_op.drop_column('trail_a_lineas_tiempo')
        batch_op.drop_column('digitos_inversos_longitud_percentil')
        batch_op.drop_column('digitos_inversos_longitud_z')
        batch_op.drop_column('digitos_inversos_total_percentil')
        batch_op.drop_column('digitos_inversos_total_z')
        batch_op.drop_column('digitos_directos_longitud_percentil')
        batch_op.drop_column('digitos_directos_longitud_z')
        batch_op.drop_column('digitos_directos_total_percentil')
        batch_op.drop_column('digitos_directos_total_z')
        batch_op.drop_column('moca_percentil')
        batch_op.drop_column('moca_z')
        batch_op.drop_column('idioma')
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
