"""Cambiar edad por fecha_nacimiento en paciente

Revision ID: f11e2efb5677
Revises: 78fe98e30ff2
Create Date: 2026-04-16 16:38:39.085590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11e2efb5677'
down_revision = '78fe98e30ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))
        batch_op.drop_column('edad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edad', sa.INTEGER(), nullable=False))
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
